spring:
  application:
    name: cctv-service

server:
  port: 8081

camera-service:
  feign-client:
    url: 'http://www.mocky.io/v2'
    available-cameras-path: '/5c51b9dd3400003252129fb5'

async:
  thread:
    pool:
      corePoolSize: 10
      maxPoolSize: 50
      queueCapacity: 50
      threadNamePrefix: "AsyncThread::"
